/** Backend: Student TCAS data + Teacher dashboard + Evidence images */
const DATA_SPREADSHEET_ID='1seV4fk00kr62MiWd9i6IxjHqVZaTLQinZmb7MDXDzc4';
const STUDENT_SPREADSHEET_ID='1gXl-v84hWWemlZ2ATEQhSPQSkxUhKmT7AlPpR0-QCIY';
const STUDENT_SHEET_NAME='Student List';
const EVIDENCE_FOLDER_ID='1BPExo71uPO1WPc1L1GP3mlK1TDDZx2Kb';
const ATTACHMENT_SHEET='attachments';
const ALLOWED_ORIGIN='https://theerawa21.github.io';
const TEACHER_SESSION_SECONDS=21600;
const CONFIG={
 activity:{sheet:'activities',headers:['citizen_id','title','first_name','last_name','program_title','exp_name','description','date','end_date','year','level','hours','fee']},
 prize:{sheet:'prizes',headers:['citizen_id','title','first_name','last_name','program_title','prize_name','description','date','end_date','year','level','hours','fee']},
 project:{sheet:'projects',headers:['citizen_id','title','first_name','last_name','project_title','project_type','description','date','end_date','year','level','hours','fee']},
 course:{sheet:'certs-courses',headers:['citizen_id','title','first_name','last_name','course_name','course_level','description','issue_date','expired_date','score','year','category','level','hours','fee','reflection']}
};
const LEVELS=['','school','district','regional','national','international'];
const ATT_HEADERS=['attachment_id','entry_id','citizen_id','student_id','class_room','type','file_id','file_name','mime_type','drive_url','created_at'];

function doGet(e){try{setupSheets_();const p=(e&&e.parameter)||{},a=String(p.action||'').trim();let r;if(a==='lookup')r=lookupStudentResponse_(p.student_id);else if(a==='records')r=recordsResponse_(p.student_id);else r={ok:true,message:'TCAS API พร้อมใช้งาน'};return jsonp_(r,p.callback)}catch(err){return jsonp_({ok:false,message:safeError_(err)},e&&e.parameter&&e.parameter.callback)}}
function doPost(e){let token='';try{setupSheets_();const p=(e&&e.parameter)||{},a=String(p.action||'').trim(),x=JSON.parse(p.payload||'{}');token=String(x._token||'');let r;if(a==='save')r=saveRecord_(x);else if(a==='update')r=updateRecord_(x);else if(a==='delete')r=deleteRecord_(x);else if(a==='teacherLogin')r=teacherLogin_(x.teacher_code);else if(a==='teacherDashboard')r=teacherDashboardResponse_(x.teacher_token);else if(a==='teacherStudent')r=teacherStudentResponse_(x.teacher_token,x.student_id);else if(a==='teacherLogout')r=teacherLogout_(x.teacher_token);else throw new Error('คำสั่งไม่ถูกต้อง');return postMessageOutput_({ok:true,token:token,result:r})}catch(err){return postMessageOutput_({ok:false,token:token,message:safeError_(err)})}}

function lookupStudentResponse_(id){const s=lookupStudent_(id);if(!s)return{ok:false,message:'ไม่พบรหัสประจำตัวนักเรียนนี้'};if(s.status&&s.status!=='กำลังศึกษาอยู่')return{ok:false,message:'ข้อมูลนักเรียนรายนี้ไม่ได้อยู่ในสถานะกำลังศึกษา'};return{ok:true,student:publicStudent_(s)}}
function recordsResponse_(id){const s=mustStudent_(id);return{ok:true,student:publicStudent_(s),records:getStudentRecords_(s)}}
function lookupStudent_(id){id=String(id||'').replace(/\D/g,'').trim();if(!id)return null;const sh=SpreadsheetApp.openById(STUDENT_SPREADSHEET_ID).getSheetByName(STUDENT_SHEET_NAME);if(!sh)throw new Error('ไม่พบชีตรายชื่อนักเรียน');const last=sh.getLastRow();if(last<4)return null;const f=sh.getRange(4,3,last-3,1).createTextFinder(id).matchEntireCell(true).findNext();if(!f)return null;const r=sh.getRange(f.getRow(),2,1,12).getDisplayValues()[0];return{citizen_id:String(r[0]||''),student_id:String(r[1]||''),class_room:String(r[2]||''),title:String(r[3]||''),first_name:String(r[4]||''),last_name:String(r[5]||''),status:String(r[10]||'')}}
function publicStudent_(s){return{student_id:s.student_id,class_room:s.class_room,title:s.title,first_name:s.first_name,last_name:s.last_name,citizen_id:s.citizen_id}}
function teacherPublicStudent_(s){return{student_id:s.student_id,class_room:s.class_room,title:s.title,first_name:s.first_name,last_name:s.last_name}}

function getStudentRecords_(s){const ss=SpreadsheetApp.openById(DATA_SPREADSHEET_ID),out=[];Object.keys(CONFIG).forEach(type=>{const c=CONFIG[type],sh=ss.getSheetByName(c.sheet);if(!sh)return;const last=sh.getLastRow();if(last<2)return;const vals=sh.getRange(2,1,last-1,c.headers.length).getDisplayValues(),notes=sh.getRange(2,1,last-1,1).getNotes();vals.forEach((r,i)=>{if(String(r[0]||'')!==s.citizen_id)return;let id=notes[i][0]||'';if(!id){id=Utilities.getUuid();sh.getRange(i+2,1).setNote(id)}const o={type:type,entry_id:id};c.headers.forEach((h,j)=>o[h]=r[j]||'');out.push(o)})});const amap=getAttachmentMap_(s.citizen_id);out.forEach(r=>r.attachments=amap[r.entry_id]||[]);return out}

function saveRecord_(p){const s=mustStudent_(p.student_id),type=mustType_(p.type),c=CONFIG[type];validate_(type,p);const lock=LockService.getScriptLock();lock.waitLock(30000);try{const sh=SpreadsheetApp.openById(DATA_SPREADSHEET_ID).getSheetByName(c.sheet),row=studentRow_(s,c,p),target=Math.max(sh.getLastRow()+1,2),id=Utilities.getUuid();sh.getRange(target,1,1,c.headers.length).setValues([row]).setVerticalAlignment('top').setWrap(true);sh.getRange(target,1).setNumberFormat('@').setNote(id);const atts=uploadEvidence_(s,type,id,String(p.year||''),p.images||[]);return{entry_id:id,attachments:atts}}finally{lock.releaseLock()}}
function updateRecord_(p){const s=mustStudent_(p.student_id),type=mustType_(p.type),c=CONFIG[type];validate_(type,p);const id=String(p.entry_id||'');if(!id)throw new Error('ไม่พบรหัสรายการ');const lock=LockService.getScriptLock();lock.waitLock(30000);try{const sh=SpreadsheetApp.openById(DATA_SPREADSHEET_ID).getSheetByName(c.sheet),row=findEntryRow_(sh,id);if(!row)throw new Error('ไม่พบรายการที่ต้องการแก้ไข');if(String(sh.getRange(row,1).getDisplayValue())!==s.citizen_id)throw new Error('ไม่มีสิทธิ์แก้ไขรายการนี้');sh.getRange(row,1,1,c.headers.length).setValues([studentRow_(s,c,p)]).setVerticalAlignment('top').setWrap(true);sh.getRange(row,1).setNumberFormat('@').setNote(id);const atts=uploadEvidence_(s,type,id,String(p.year||''),p.images||[]);return{entry_id:id,attachments:atts}}finally{lock.releaseLock()}}
function deleteRecord_(p){const s=mustStudent_(p.student_id),id=String(p.entry_id||'');if(!id)throw new Error('ไม่พบรหัสรายการ');const lock=LockService.getScriptLock();lock.waitLock(30000);try{const ss=SpreadsheetApp.openById(DATA_SPREADSHEET_ID);for(const type of Object.keys(CONFIG)){const sh=ss.getSheetByName(CONFIG[type].sheet),row=findEntryRow_(sh,id);if(!row)continue;if(String(sh.getRange(row,1).getDisplayValue())!==s.citizen_id)throw new Error('ไม่มีสิทธิ์ลบรายการนี้');deleteAttachmentsForEntry_(id,s.citizen_id);sh.deleteRow(row);return{entry_id:id}}throw new Error('ไม่พบรายการที่ต้องการลบ')}finally{lock.releaseLock()}}

/* Evidence images: stored separately so 4 TCAS tables remain unchanged */
function uploadEvidence_(s,type,entryId,year,images){if(!Array.isArray(images)||!images.length)return[];if(images.length>4)throw new Error('แนบภาพได้ไม่เกิน 4 ภาพต่อครั้ง');const root=DriveApp.getFolderById(EVIDENCE_FOLDER_ID),yf=getOrCreateFolder_(root,safeFolder_(year||'ไม่ระบุปี')),rf=getOrCreateFolder_(yf,safeFolder_(s.class_room||'ไม่ระบุห้อง')),sf=getOrCreateFolder_(rf,safeFolder_(s.student_id+'_'+s.first_name+'_'+s.last_name)),tf=getOrCreateFolder_(sf,type);const ss=SpreadsheetApp.openById(DATA_SPREADSHEET_ID),sh=ss.getSheetByName(ATTACHMENT_SHEET),rows=[],out=[];images.forEach((img,i)=>{const data=String(img.data||''),m=data.match(/^data:(image\/[a-zA-Z0-9.+-]+);base64,(.+)$/);if(!m)throw new Error('รูปแบบไฟล์ภาพไม่ถูกต้อง');if(m[2].length>3500000)throw new Error('ภาพมีขนาดใหญ่เกินไป กรุณาเลือกภาพใหม่');const mime=m[1],bytes=Utilities.base64Decode(m[2]),ext=mime.indexOf('png')>-1?'png':mime.indexOf('webp')>-1?'webp':'jpg',fname=s.student_id+'_'+type+'_'+Utilities.formatDate(new Date(),'Asia/Bangkok','yyyyMMdd_HHmmss')+'_'+(i+1)+'.'+ext,blob=Utilities.newBlob(bytes,mime,fname),file=tf.createFile(blob),aid=Utilities.getUuid(),url=file.getUrl(),created=Utilities.formatDate(new Date(),'Asia/Bangkok','dd/MM/yyyy HH:mm:ss');rows.push([aid,entryId,s.citizen_id,s.student_id,s.class_room,type,file.getId(),fname,mime,url,created]);out.push({attachment_id:aid,file_name:fname,mime_type:mime,drive_url:url,created_at:created})});if(rows.length)sh.getRange(sh.getLastRow()+1,1,rows.length,ATT_HEADERS.length).setValues(rows);return out}
function getAttachmentMap_(citizen){const sh=SpreadsheetApp.openById(DATA_SPREADSHEET_ID).getSheetByName(ATTACHMENT_SHEET),map={};if(!sh||sh.getLastRow()<2)return map;const vals=sh.getRange(2,1,sh.getLastRow()-1,ATT_HEADERS.length).getDisplayValues();vals.forEach(r=>{if(String(r[2]||'')!==citizen)return;const x={attachment_id:r[0],file_name:r[7],mime_type:r[8],drive_url:r[9],created_at:r[10]};if(!map[r[1]])map[r[1]]=[];map[r[1]].push(x)});return map}
function deleteAttachmentsForEntry_(entryId,citizen){const sh=SpreadsheetApp.openById(DATA_SPREADSHEET_ID).getSheetByName(ATTACHMENT_SHEET);if(!sh||sh.getLastRow()<2)return;const vals=sh.getRange(2,1,sh.getLastRow()-1,ATT_HEADERS.length).getDisplayValues();for(let i=vals.length-1;i>=0;i--){const r=vals[i];if(r[1]===entryId&&r[2]===citizen){try{DriveApp.getFileById(r[6]).setTrashed(true)}catch(_){ }sh.deleteRow(i+2)}}}
function getOrCreateFolder_(parent,name){const it=parent.getFoldersByName(name);return it.hasNext()?it.next():parent.createFolder(name)}
function safeFolder_(v){return String(v||'').replace(/[\\/:*?"<>|]/g,'-').trim()||'ไม่ระบุ'}

/* Teacher mode */
function teacherLogin_(code){const value=String(code||'').trim(),expected=getTeacherCode_();if(!value||value!==expected)throw new Error('รหัสสำหรับครูไม่ถูกต้อง');const session=Utilities.getUuid().replace(/-/g,'');CacheService.getScriptCache().put('teacher:'+session,'1',TEACHER_SESSION_SECONDS);return{teacher_token:session,dashboard:teacherDashboardData_()}}
function teacherDashboardResponse_(session){requireTeacherSession_(session);refreshTeacherSession_(session);return teacherDashboardData_()}
function teacherStudentResponse_(session,id){requireTeacherSession_(session);refreshTeacherSession_(session);const s=mustStudent_(id);return{student:teacherPublicStudent_(s),records:getStudentRecords_(s).map(teacherRecord_)}}
function teacherLogout_(session){CacheService.getScriptCache().remove('teacher:'+String(session||''));return{success:true}}
function getTeacherCode_(){const c=PropertiesService.getScriptProperties().getProperty('TEACHER_CODE');if(!c)throw new Error('ยังไม่ได้ตั้งค่า TEACHER_CODE ใน Script Properties');return String(c).trim()}
function requireTeacherSession_(s){const t=String(s||'').trim();if(!t||CacheService.getScriptCache().get('teacher:'+t)!=='1')throw new Error('สิทธิ์ครูหมดอายุ กรุณาเข้าสู่ระบบใหม่')}
function refreshTeacherSession_(s){CacheService.getScriptCache().put('teacher:'+String(s||''),'1',TEACHER_SESSION_SECONDS)}
function getAllActiveStudents_(){const sh=SpreadsheetApp.openById(STUDENT_SPREADSHEET_ID).getSheetByName(STUDENT_SHEET_NAME);if(!sh)throw new Error('ไม่พบชีตรายชื่อนักเรียน');const last=sh.getLastRow();if(last<4)return[];return sh.getRange(4,2,last-3,12).getDisplayValues().map(r=>({citizen_id:String(r[0]||'').trim(),student_id:String(r[1]||'').trim(),class_room:String(r[2]||'').trim(),title:String(r[3]||'').trim(),first_name:String(r[4]||'').trim(),last_name:String(r[5]||'').trim(),status:String(r[10]||'').trim()})).filter(s=>s.student_id&&(!s.status||s.status==='กำลังศึกษาอยู่'))}
function buildRecordCountMap_(){const ss=SpreadsheetApp.openById(DATA_SPREADSHEET_ID),map={};Object.keys(CONFIG).forEach(type=>{const sh=ss.getSheetByName(CONFIG[type].sheet);if(!sh||sh.getLastRow()<2)return;sh.getRange(2,1,sh.getLastRow()-1,1).getDisplayValues().forEach(r=>{const c=String(r[0]||'').trim();if(!c)return;if(!map[c])map[c]={activity:0,prize:0,project:0,course:0,total:0};map[c][type]++;map[c].total++})});return map}
function teacherDashboardData_(){const students=getAllActiveStudents_(),m=buildRecordCountMap_(),list=students.map(s=>{const c=m[s.citizen_id]||{activity:0,prize:0,project:0,course:0,total:0};return{student_id:s.student_id,class_room:s.class_room,title:s.title,first_name:s.first_name,last_name:s.last_name,submitted:c.total>0,total_records:c.total,counts:{activity:c.activity||0,prize:c.prize||0,project:c.project||0,course:c.course||0}}});list.sort((a,b)=>String(a.class_room).localeCompare(String(b.class_room),'th')||Number(a.student_id||0)-Number(b.student_id||0));const rm={};list.forEach(s=>{const r=s.class_room||'ไม่ระบุห้อง';if(!rm[r])rm[r]={class_room:r,total:0,submitted:0,not_submitted:0,records:0};rm[r].total++;rm[r].records+=Number(s.total_records||0);if(s.total_records>0)rm[r].submitted++;else rm[r].not_submitted++});const rooms=Object.keys(rm).sort().map(k=>rm[k]),submitted=list.filter(s=>s.total_records>0).length;return{generated_at:Utilities.formatDate(new Date(),'Asia/Bangkok','dd/MM/yyyy HH:mm:ss'),total_students:list.length,submitted_students:submitted,not_submitted_students:list.length-submitted,total_records:list.reduce((a,s)=>a+Number(s.total_records||0),0),rooms:rooms,students:list}}
function teacherRecord_(r){const o={};Object.keys(r).forEach(k=>{if(['citizen_id','title','first_name','last_name'].indexOf(k)===-1)o[k]=r[k]});return o}

/* Common helpers */
function findEntryRow_(sh,id){const last=sh.getLastRow();if(last<2)return 0;const n=sh.getRange(2,1,last-1,1).getNotes();for(let i=0;i<n.length;i++)if(n[i][0]===id)return i+2;return 0}
function studentRow_(s,c,p){const src=Object.assign({},p,{citizen_id:s.citizen_id,title:s.title,first_name:s.first_name,last_name:s.last_name});return c.headers.map(h=>normalize_(src[h]))}
function mustStudent_(id){const s=lookupStudent_(id);if(!s)throw new Error('ไม่พบข้อมูลนักเรียน');if(s.status&&s.status!=='กำลังศึกษาอยู่')throw new Error('สถานะนักเรียนไม่ถูกต้อง');return s}
function mustType_(t){const v=String(t||'');if(!CONFIG[v])throw new Error('ประเภทข้อมูลไม่ถูกต้อง');return v}
function validate_(type,p){if(!String(p.year||'').trim())throw new Error('กรุณาระบุปีการศึกษา');if(p.level&&!LEVELS.includes(String(p.level)))throw new Error('ระดับข้อมูลไม่ถูกต้อง');if(type==='activity'&&(!p.program_title||!p.exp_name||!p.date))throw new Error('กรุณากรอกชื่อกิจกรรม บทบาท และวันที่เริ่ม');if(type==='prize'&&(!p.program_title||!p.prize_name||!p.date))throw new Error('กรุณากรอกชื่อการแข่งขัน รางวัล และวันที่');if(type==='project'&&(!p.project_title||!p.project_type||!p.date))throw new Error('กรุณากรอกชื่อโครงงาน ประเภท และวันที่เริ่ม');if(type==='course'&&(!p.course_name||!p.issue_date))throw new Error('กรุณากรอกชื่อหลักสูตรและวันที่ออกใบรับรอง')}
function normalize_(v){return v===null||v===undefined?'':String(v).trim()}
function setupSheets_(){const ss=SpreadsheetApp.openById(DATA_SPREADSHEET_ID);Object.keys(CONFIG).forEach(type=>{const c=CONFIG[type];let sh=ss.getSheetByName(c.sheet);if(!sh)sh=ss.insertSheet(c.sheet);if(sh.getMaxColumns()<c.headers.length)sh.insertColumnsAfter(sh.getMaxColumns(),c.headers.length-sh.getMaxColumns());const head=sh.getRange(1,1,1,c.headers.length),old=head.getDisplayValues()[0];if(c.headers.some((h,i)=>old[i]!==h))head.setValues([c.headers]);head.setBackground('#17365D').setFontColor('#FFFFFF').setFontWeight('bold').setHorizontalAlignment('center').setVerticalAlignment('middle').setWrap(true);sh.setFrozenRows(1);sh.getRange('A:A').setNumberFormat('@');const col=c.headers.indexOf('level')+1;if(col>0){const rule=SpreadsheetApp.newDataValidation().requireValueInList(['school','district','regional','national','international'],true).setAllowInvalid(false).build();sh.getRange(2,col,Math.max(sh.getMaxRows()-1,1),1).setDataValidation(rule)}});let a=ss.getSheetByName(ATTACHMENT_SHEET);if(!a)a=ss.insertSheet(ATTACHMENT_SHEET);if(a.getMaxColumns()<ATT_HEADERS.length)a.insertColumnsAfter(a.getMaxColumns(),ATT_HEADERS.length-a.getMaxColumns());const ah=a.getRange(1,1,1,ATT_HEADERS.length),av=ah.getDisplayValues()[0];if(ATT_HEADERS.some((h,i)=>av[i]!==h))ah.setValues([ATT_HEADERS]);ah.setBackground('#6B4F9C').setFontColor('#FFFFFF').setFontWeight('bold').setWrap(true);a.setFrozenRows(1);a.getRange('C:C').setNumberFormat('@')}
function setupSheets(){setupSheets_();return'พร้อมใช้งาน'}
function jsonp_(o,cb){const c=String(cb||'').replace(/[^a-zA-Z0-9_$.]/g,''),j=JSON.stringify(o);return ContentService.createTextOutput(c?c+'('+j+');':j).setMimeType(c?ContentService.MimeType.JAVASCRIPT:ContentService.MimeType.JSON)}
function postMessageOutput_(o){const d=JSON.stringify(Object.assign({source:'tcas-apps-script'},o)).replace(/</g,'\\u003c'),h='<!doctype html><meta charset="utf-8"><script>window.parent.postMessage('+d+','+JSON.stringify(ALLOWED_ORIGIN)+');<\/script>';return HtmlService.createHtmlOutput(h).setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)}
function safeError_(e){return e&&e.message?String(e.message):'เกิดข้อผิดพลาดของระบบ'}