(()=>{'use strict';
const $=id=>document.getElementById(id);
const TYPES={activity:{label:'กิจกรรม',icon:'🏃'},prize:{label:'รางวัล',icon:'🏆'},project:{label:'โครงงาน',icon:'💡'},course:{label:'หลักสูตร / Certificate',icon:'📜'}};
const LABELS={program_title:'ชื่อกิจกรรม / การแข่งขัน',exp_name:'บทบาท / ผลที่ได้รับ',prize_name:'รางวัลที่ได้รับ',project_title:'ชื่อโครงงาน',project_type:'ประเภทโครงงาน',course_name:'ชื่อหลักสูตร / การอบรม',course_level:'ระดับหลักสูตร',category:'ประเภทหลักสูตร',description:'รายละเอียด',date:'วันที่เริ่ม / วันที่ได้รับ',end_date:'วันที่สิ้นสุด',issue_date:'วันที่ออกใบรับรอง',expired_date:'วันหมดอายุ',score:'ผลการอบรม / คะแนน',year:'ปีการศึกษา',level:'ระดับ',hours:'จำนวนชั่วโมง',fee:'ค่าใช้จ่าย',reflection:'Reflection / สิ่งที่ได้รับ'};
const HIDE_IDS=['setupView','loginView','confirmView','dashboardView','formView','teacherLoginView','teacherDashboardView','teacherDetailView'];
let teacherToken='',data=null,selectedRoom='all',statusFilter='all',typeFilter='all',searchText='';
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const name=s=>`${s.title||''}${s.first_name||''} ${s.last_name||''}`.trim();
const recordTitle=r=>r.program_title||r.project_title||r.course_name||'-';
function hideAll(){HIDE_IDS.forEach(id=>{const el=$(id);if(el)el.classList.add('hidden')});if($('logoutBtn'))$('logoutBtn').classList.add('hidden')}
function showTeacher(id){hideAll();$(id).classList.remove('hidden');$('teacherEntryBtn').classList.toggle('hidden',id!=='loginView');window.scrollTo({top:0,behavior:'smooth'})}
function showStudentLogin(){hideAll();$('loginView').classList.remove('hidden');$('teacherEntryBtn').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function loading(on){$('loader')?.classList.toggle('show',!!on)}
function toast(msg){const e=$('toast');if(!e)return;e.textContent=msg;e.classList.add('show');clearTimeout(e._teacherT);e._teacherT=setTimeout(()=>e.classList.remove('show'),2600)}
function postTeacher(action,payload={}){return new Promise((resolve,reject)=>{const api=(window.TCAS_CONFIG&&window.TCAS_CONFIG.apiUrl)||localStorage.getItem('tcas_api_url')||'';if(!api){reject(new Error('ไม่พบการเชื่อมต่อฐานข้อมูล'));return}const token='t_'+Date.now()+'_'+Math.random().toString(36).slice(2);const form=$('postForm');const frame=$('postFrame');if(!form||!frame){reject(new Error('ไม่พบฟอร์มเชื่อมต่อ'));return}let timer;const handler=e=>{if(!e.data||e.data.source!=='tcas-apps-script'||e.data.token!==token)return;window.removeEventListener('message',handler);clearTimeout(timer);e.data.ok?resolve(e.data.result):reject(new Error(e.data.message||'เกิดข้อผิดพลาด'))};window.addEventListener('message',handler);form.action=api;form.elements.action.value=action;form.elements.payload.value=JSON.stringify({...payload,_token:token});form.elements.origin.value=location.origin;timer=setTimeout(()=>{window.removeEventListener('message',handler);reject(new Error('หมดเวลาการเชื่อมต่อ กรุณาลองใหม่'))},30000);form.submit()})}
function countsOf(list){const c={total:list.length,submitted:0,notSubmitted:0,records:0};list.forEach(s=>{const n=Number(s.total_records||0);c.records+=n;n>0?c.submitted++:c.notSubmitted++});return c}
function filteredStudents(){if(!data)return[];return data.students.filter(s=>{if(selectedRoom!=='all'&&s.class_room!==selectedRoom)return false;const submitted=Number(s.total_records||0)>0;if(statusFilter==='sent'&&!submitted)return false;if(statusFilter==='none'&&submitted)return false;if(typeFilter!=='all'&&Number((s.counts||{})[typeFilter]||0)<1)return false;const q=searchText.trim().toLowerCase();if(q){const hay=`${s.student_id} ${s.title||''}${s.first_name||''} ${s.last_name||''}`.toLowerCase();if(!hay.includes(q))return false}return true})}
function roomStudents(){if(!data)return[];return selectedRoom==='all'?data.students:data.students.filter(s=>s.class_room===selectedRoom)}
function renderStats(){const c=countsOf(roomStudents());$('teacherTotal').textContent=c.total;$('teacherSent').textContent=c.submitted;$('teacherNotSent').textContent=c.notSubmitted;$('teacherRecords').textContent=c.records;$('teacherScopeLabel').textContent=selectedRoom==='all'?'ทุกห้อง':selectedRoom}
function renderRooms(){const wrap=$('teacherRoomGrid');if(!wrap||!data)return;const all=countsOf(data.students);let html=`<button class="room-card ${selectedRoom==='all'?'active':''}" data-room="all"><div class="room-name">ทุกห้อง</div><div class="room-meta">${all.submitted}/${all.total} คนส่งแล้ว · ${all.records} รายการ</div></button>`;html+=data.rooms.map(r=>`<button class="room-card ${selectedRoom===r.class_room?'active':''}" data-room="${esc(r.class_room)}"><div class="room-name">${esc(r.class_room)}</div><div class="room-meta">${r.submitted}/${r.total} คนส่งแล้ว · ยังไม่ส่ง ${r.not_submitted} คน<br>${r.records} รายการ</div></button>`).join('');wrap.innerHTML=html;wrap.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>{selectedRoom=b.dataset.room;renderAll()})}
function renderStudents(){const list=filteredStudents(),tbody=$('teacherStudentRows');$('teacherResultCount').textContent=`${list.length} คน`;if(!list.length){tbody.innerHTML='<tr><td colspan="5"><div class="teacher-empty">ไม่พบนักเรียนตามเงื่อนไขที่เลือก</div></td></tr>';return}tbody.innerHTML=list.map(s=>{const c=s.counts||{},sent=Number(s.total_records||0)>0;return `<tr><td><div class="student-main"><strong>${esc(name(s))}</strong><span>รหัส ${esc(s.student_id)} · ${esc(s.class_room||'-')}</span></div></td><td><span class="status-pill ${sent?'status-sent':'status-none'}">${sent?'✓ ส่งแล้ว':'ยังไม่ส่ง'}</span></td><td><strong>${Number(s.total_records||0)}</strong> รายการ</td><td><div class="record-badges"><span class="record-badge">🏃 ${Number(c.activity||0)}</span><span class="record-badge">🏆 ${Number(c.prize||0)}</span><span class="record-badge">💡 ${Number(c.project||0)}</span><span class="record-badge">📜 ${Number(c.course||0)}</span></div></td><td><button class="btn btn-secondary teacher-detail-btn" data-student="${esc(s.student_id)}" ${sent?'':'disabled'}>ดูรายละเอียด</button></td></tr>`}).join('');tbody.querySelectorAll('.teacher-detail-btn:not([disabled])').forEach(b=>b.onclick=()=>openStudentDetail(b.dataset.student))}
function renderAll(){renderStats();renderRooms();renderStudents()}
async function openStudentDetail(studentId){loading(1);try{const res=await postTeacher('teacherStudent',{teacher_token:teacherToken,student_id:studentId});renderDetail(res);showTeacher('teacherDetailView')}catch(e){toast(e.message)}finally{loading(0)}}
function renderDetail(res){const s=res.student||{},records=res.records||[];$('teacherDetailName').textContent=name(s);$('teacherDetailMeta').textContent=`รหัส ${s.student_id||'-'} · ${s.class_room||'-'} · ${records.length} รายการ`;const wrap=$('teacherRecordList');if(!records.length){wrap.innerHTML='<div class="teacher-empty">นักเรียนคนนี้ยังไม่มีข้อมูลที่บันทึก</div>';return}wrap.innerHTML=records.map(r=>{const type=TYPES[r.type]||{label:r.type||'รายการ',icon:'📄'};const fields=Object.keys(LABELS).filter(k=>r[k]!==undefined&&String(r[k]).trim()!=='').map(k=>`<div class="teacher-record-field"><div class="k">${esc(LABELS[k])}</div><div class="v">${esc(r[k])}</div></div>`).join('');return `<div class="teacher-record"><div class="teacher-record-top"><div><div class="teacher-record-title">${type.icon} ${esc(recordTitle(r))}</div></div><span class="teacher-record-kind">${esc(type.label)}</span></div><div class="teacher-record-grid">${fields}</div></div>`}).join('')}
$('teacherEntryBtn')?.addEventListener('click',()=>{teacherToken='';$('teacherCode').value='';$('teacherLoginError').classList.add('hidden');showTeacher('teacherLoginView')});
$('teacherBackStudentBtn')?.addEventListener('click',showStudentLogin);
$('teacherLoginForm')?.addEventListener('submit',async e=>{e.preventDefault();const code=$('teacherCode').value.trim();$('teacherLoginError').classList.add('hidden');if(!code)return;loading(1);try{const res=await postTeacher('teacherLogin',{teacher_code:code});teacherToken=res.teacher_token;data=res.dashboard;selectedRoom='all';statusFilter='all';typeFilter='all';searchText='';$('teacherSearch').value='';$('teacherStatus').value='all';$('teacherType').value='all';renderAll();showTeacher('teacherDashboardView')}catch(err){$('teacherLoginError').textContent=err.message;$('teacherLoginError').classList.remove('hidden')}finally{loading(0)}});
$('teacherRefreshBtn')?.addEventListener('click',async()=>{if(!teacherToken)return;loading(1);try{data=await postTeacher('teacherDashboard',{teacher_token:teacherToken});renderAll();toast('อัปเดตข้อมูลแล้ว')}catch(e){toast(e.message)}finally{loading(0)}});
$('teacherLogoutBtn')?.addEventListener('click',async()=>{try{if(teacherToken)await postTeacher('teacherLogout',{teacher_token:teacherToken})}catch(_){ }teacherToken='';data=null;showStudentLogin()});
$('teacherSearch')?.addEventListener('input',e=>{searchText=e.target.value;renderStudents()});
$('teacherStatus')?.addEventListener('change',e=>{statusFilter=e.target.value;renderStudents()});
$('teacherType')?.addEventListener('change',e=>{typeFilter=e.target.value;renderStudents()});
$('teacherDetailBackBtn')?.addEventListener('click',()=>showTeacher('teacherDashboardView'));
})();